development:
  adapter: postgresql
  database: newapp_development
  encoding: unicode
  pool: 5
  username: newapp
  password: root

test: &test
  adapter: postgresql
  database: newapp_test
  encoding: unicode
  pool: 5
  username: newapp
  password: root

production:


cucumber:
  <<: *test